version: "2.4"

services:
  elasticsearch:
    container_name: elasticsearch-custom-okt
    image: es-okt-tokenizer:7.17.4-okt-2.1.0
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/network.host.html
    # Set Xmx and Xms to no more than 50% of your physical RAM.
    environment:
      - cluster.name=docker-cluster
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9201:9200
      - 9300:9300